name: mynotes
description: A new Flutter project.


publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  file_picker: ^4.0.3
  open_file: ^3.2.1
  firebase_storage: ^10.0.3
  cloud_firestore: ^2.2.1
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.2.1
  firebase_auth: ^3.3.9
  flutter_datetime_picker: ^1.5.1
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  path: ^1.8.0
  get:
  image_picker: ^0.8.4+11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "assets/img_1.png"

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: Italic
      fonts:
        - asset: assets/italic.ttf

    - family: Bold
      fonts:
        - asset: assets/bold.ttf
