// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn6HogY1DlOfS2U_37Dlpg7POKEnysI_k',
    appId: '1:632601047346:android:216a36cd625b205763672b',
    messagingSenderId: '632601047346',
    projectId: 'mynotes-dev-sidney',
    storageBucket: 'mynotes-dev-sidney.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jJE9vQpmx2MwJsA4Y_q6d93DQnQEgyc',
    appId: '1:632601047346:ios:174b29d3304994e163672b',
    messagingSenderId: '632601047346',
    projectId: 'mynotes-dev-sidney',
    storageBucket: 'mynotes-dev-sidney.appspot.com',
    iosClientId: '632601047346-3jv7i7mbic1m8g5pmnesqh51k455jcci.apps.googleusercontent.com',
    iosBundleId: 'dev.sidney.mynotes',
  );
}
